.TH "GUZUTA" "1" "January 2010" "Arch Linux" "User Manuals"
.SH "NAME"
guzuta \- An AUR helper that creates a local repo from which pacman installs packages.

.SH "SYNOPSIS"
guzuta \-S <package name> ...

guzuta \-Su

guzuta \-U path/to/taurball.tar.gz ...
.SH "DESCRIPTION"
guzuta is an AUR helper that places built packages into a local repo where
.BR pacman (8)
can install from.
.SH "OPTIONS"
.TP
\fB\-S\fR, \fB\-\-sync\fR
Sychronise specified package list from AUR, resolving AUR dependencies, and add the built packages to the local repo.
.TP
\fB\-u\fR, \fB\-\-update\fR
When passed with \-S, check the AUR for updates to packages in the local repo and build 
them.
.TP
\fB\-s\fR, \fB\-\-search\fR
When passed with \-S, perform a search of the AUR for the string provided.
.TP
\fB\-U\fR, \fB\-\-upgrade\fR
Build packages from specified taurballs and add them to the local repo.
.SH "FILES"
.I /etc/guzuta.conf
.RS
The system-wide configuration file.
.SH "AUTHORS"
Joseph R. Nosie <bolts at archlinux dot us>
.SH "SEE ALSO"
.BR pacman (8),
.BR makepkg (8)
